spring.application.name=Customers
logging.level.root=INFO
logging.level.ch.customers=DEBUG
logging.file.name=logs/app.log

spring.datasource.name=${DB_NAME:customers}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:Admin$00}